# You can raise an exception any time you want to:
# Here we raise an exception of type Exception which accepts a string argument
raise Exception ('"Exception was raised and this string passed in as argument"')
# the print will not happen as the exception quit the program
print('after the exception')

